{% set name = "sagemaker-jupyterlab-extension" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker-jupyterlab-extension-{{ version }}.tar.gz
  sha256: 5d3d21ecb235e5d8b4af58de8d7942cebfbaaeb02ae45e6aa3929265728808a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >=3.9
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - sagemaker-jupyterlab-extension-common
    - async-lru
    - aws-embedded-metrics

test:
  imports:
    - sagemaker_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab workspace primary extension module
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zuoyuanh
